### ISSUE TITLE
java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by xtjie2001** [jobfeikens/rcon#6]
## Environment：
```java
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b06, mixed mode)

SpringBoot
```

## Actual behaviour:
run and test

## raises an error
```
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at nl.vv32.rcon.PacketWriter.write(PacketWriter.java:26) ~[rcon-1.2.0.jar:na]
	at nl.vv32.rcon.Rcon.writeAndRead(Rcon.java:76) ~[rcon-1.2.0.jar:na]
	at nl.vv32.rcon.Rcon.authenticate(Rcon.java:42) ~[rcon-1.2.0.jar:na]
	at top.xtijie.authmercon.config.RconConfig.rcon(RconConfig.java:51) ~[classes/:na]
	at top.xtijie.authmercon.config.RconConfig$$EnhancerBySpringCGLIB$$2b527bbf.CGLIB$rcon$1(<generated>) ~[classes/:na]
	at top.xtijie.authmercon.config.RconConfig$$EnhancerBySpringCGLIB$$2b527bbf$$FastClassBySpringCGLIB$$750833f9.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.23.jar:5.3.23]
	at top.xtijie.authmercon.config.RconConfig$$EnhancerBySpringCGLIB$$2b527bbf.rcon(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_322]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_322]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_322]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_322]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.23.jar:5.3.23]
	... 19 common frames omitted
```

## other
if use jdk 11 and above then there is no problem.
if use jdk 1.8 will go wrong.

**Comment by xtjie2001** [comment]
> ## Environment：
> ```java
> openjdk version "1.8.0_322"
> OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
> OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b06, mixed mode)
> 
> SpringBoot
> ```
> 
> ## Actual behaviour:
> run and test
> 
> ## raises an error
> ```
> Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
> 	at nl.vv32.rcon.PacketWriter.write(PacketWriter.java:26) ~[rcon-1.2.0.jar:na]
> 	at nl.vv32.rcon.Rcon.writeAndRead(Rcon.java:76) ~[rcon-1.2.0.jar:na]
> 	at nl.vv32.rcon.Rcon.authenticate(Rcon.java:42) ~[rcon-1.2.0.jar:na]
> 	at top.xtijie.authmercon.config.RconConfig.rcon(RconConfig.java:51) ~[classes/:na]
> 	at top.xtijie.authmercon.config.RconConfig$$EnhancerBySpringCGLIB$$2b527bbf.CGLIB$rcon$1(<generated>) ~[classes/:na]
> 	at top.xtijie.authmercon.config.RconConfig$$EnhancerBySpringCGLIB$$2b527bbf$$FastClassBySpringCGLIB$$750833f9.invoke(<generated>) ~[classes/:na]
> 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.23.jar:5.3.23]
> 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.23.jar:5.3.23]
> 	at top.xtijie.authmercon.config.RconConfig$$EnhancerBySpringCGLIB$$2b527bbf.rcon(<generated>) ~[classes/:na]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_322]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_322]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_322]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_322]
> 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.23.jar:5.3.23]
> 	... 19 common frames omitted
> ```
> 
> ## other
> if use jdk 11 and above then there is no problem. if use jdk 1.8 will go wrong.

## The location of the error was reported
```java
nl.vv32.rcon.Rcon.authenticate(String password)
```

**Comment by jobfeikens** [comment]
Looks like the same issue as #2. Thought it was fixed :)
I'll look into it later this week
